"""
PlantIQ — Alert Store
========================
Component 3.4 — Alert Acknowledgement System with 6-state lifecycle.

Every alert passes through six states:
  1. fired       — Alert generated by system
  2. delivered   — Pushed to operator dashboard
  3. seen        — Operator opened the panel
  4. acknowledged — Operator explicitly acknowledged
  5. acted_upon  — Operator took action (followed / declined / escalated)
  6. resolved    — Issue confirmed resolved

Escalation rules:
  - If not seen within 10 min → escalate to supervisor
  - If supervisor doesn't ack within 5 min → escalate to plant manager
"""

from __future__ import annotations

import uuid
from datetime import datetime, timedelta
from typing import Dict, List, Optional

from sqlalchemy.orm import Session

from database.models import AlertRecord, AuditLog


VALID_STATES = ["fired", "delivered", "seen", "acknowledged", "acted_upon", "resolved"]
STATE_ORDER = {s: i for i, s in enumerate(VALID_STATES)}
VALID_ACTIONS = ["followed", "declined", "escalated"]

# Escalation timeouts
ESCALATION_TO_SUPERVISOR_MINUTES = 10
ESCALATION_TO_PLANT_MANAGER_MINUTES = 5


def _generate_alert_id() -> str:
    return f"ALERT_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}_{uuid.uuid4().hex[:4].upper()}"


def fire_alert(
    db: Session,
    *,
    batch_id: str,
    alert_type: str,
    severity: str,
    message: str,
    technical_detail: Optional[str] = None,
    recommended_action: Optional[str] = None,
    estimated_saving_kwh: Optional[float] = None,
    quality_impact_pct: Optional[float] = None,
) -> AlertRecord:
    """Create a new alert in 'fired' state."""
    alert_id = _generate_alert_id()

    alert = AlertRecord(
        alert_id=alert_id,
        batch_id=batch_id,
        alert_type=alert_type,
        severity=severity,
        message=message,
        technical_detail=technical_detail,
        recommended_action=recommended_action,
        estimated_saving_kwh=estimated_saving_kwh,
        quality_impact_pct=quality_impact_pct,
        state="fired",
        fired_at=datetime.utcnow(),
    )
    db.add(alert)

    audit = AuditLog(
        event_type="alert_fired",
        batch_id=batch_id,
        details={
            "alert_id": alert_id,
            "alert_type": alert_type,
            "severity": severity,
            "message": message,
        },
    )
    db.add(audit)

    db.commit()
    db.refresh(alert)
    return alert


def transition_alert(
    db: Session,
    alert_id: str,
    new_state: str,
    *,
    actor: Optional[str] = None,
    action_taken: Optional[str] = None,
    action_note: Optional[str] = None,
) -> AlertRecord:
    """Advance an alert to a new lifecycle state.

    States must progress forward — no backward transitions allowed.
    """
    if new_state not in VALID_STATES:
        raise ValueError(f"Invalid state: {new_state}. Must be one of {VALID_STATES}")

    alert = db.query(AlertRecord).filter(AlertRecord.alert_id == alert_id).first()
    if alert is None:
        raise ValueError(f"Alert not found: {alert_id}")

    current_order = STATE_ORDER.get(alert.state, 0)
    new_order = STATE_ORDER.get(new_state, 0)
    if new_order <= current_order:
        raise ValueError(
            f"Cannot transition from '{alert.state}' to '{new_state}'. "
            f"States must progress forward."
        )

    now = datetime.utcnow()
    alert.state = new_state

    if new_state == "delivered":
        alert.delivered_at = now
    elif new_state == "seen":
        alert.seen_at = now
    elif new_state == "acknowledged":
        alert.acknowledged_at = now
        alert.acknowledged_by = actor
    elif new_state == "acted_upon":
        alert.acted_upon_at = now
        if action_taken and action_taken in VALID_ACTIONS:
            alert.action_taken = action_taken
        alert.action_note = action_note
    elif new_state == "resolved":
        alert.resolved_at = now

    audit = AuditLog(
        event_type="alert_acknowledged" if new_state == "acknowledged" else f"alert_{new_state}",
        batch_id=alert.batch_id,
        actor=actor,
        details={
            "alert_id": alert_id,
            "new_state": new_state,
            "action_taken": action_taken,
            "action_note": action_note,
        },
    )
    db.add(audit)

    db.commit()
    db.refresh(alert)
    return alert


def escalate_alert(
    db: Session,
    alert_id: str,
    escalate_to: str,
) -> AlertRecord:
    """Escalate an alert to supervisor or plant manager."""
    alert = db.query(AlertRecord).filter(AlertRecord.alert_id == alert_id).first()
    if alert is None:
        raise ValueError(f"Alert not found: {alert_id}")

    alert.escalation_level = min(alert.escalation_level + 1, 2)
    alert.escalated_at = datetime.utcnow()
    alert.escalated_to = escalate_to

    audit = AuditLog(
        event_type="alert_escalated",
        batch_id=alert.batch_id,
        details={
            "alert_id": alert_id,
            "escalation_level": alert.escalation_level,
            "escalated_to": escalate_to,
        },
    )
    db.add(audit)

    db.commit()
    db.refresh(alert)
    return alert


def check_escalations(db: Session) -> List[AlertRecord]:
    """Check for alerts that need escalation due to timeout.

    Returns list of alerts that were escalated.
    """
    now = datetime.utcnow()
    escalated = []

    # Level 0 → 1: fired but not seen within 10 min
    supervisor_cutoff = now - timedelta(minutes=ESCALATION_TO_SUPERVISOR_MINUTES)
    stale_fired = (
        db.query(AlertRecord)
        .filter(
            AlertRecord.state.in_(["fired", "delivered"]),
            AlertRecord.escalation_level == 0,
            AlertRecord.fired_at <= supervisor_cutoff,
        )
        .all()
    )
    for alert in stale_fired:
        escalate_alert(db, alert.alert_id, "shift_supervisor")
        escalated.append(alert)

    # Level 1 → 2: supervisor notified but not acked within 5 min
    manager_cutoff = now - timedelta(minutes=ESCALATION_TO_PLANT_MANAGER_MINUTES)
    stale_supervisor = (
        db.query(AlertRecord)
        .filter(
            AlertRecord.state.in_(["fired", "delivered", "seen"]),
            AlertRecord.escalation_level == 1,
            AlertRecord.escalated_at <= manager_cutoff,
        )
        .all()
    )
    for alert in stale_supervisor:
        escalate_alert(db, alert.alert_id, "plant_manager")
        escalated.append(alert)

    return escalated


def get_alert(db: Session, alert_id: str) -> Optional[AlertRecord]:
    """Retrieve a single alert by ID."""
    return db.query(AlertRecord).filter(AlertRecord.alert_id == alert_id).first()


def get_alerts_for_batch(db: Session, batch_id: str) -> List[AlertRecord]:
    """Get all alerts for a specific batch."""
    return (
        db.query(AlertRecord)
        .filter(AlertRecord.batch_id == batch_id)
        .order_by(AlertRecord.fired_at.desc())
        .all()
    )


def list_active_alerts(
    db: Session,
    *,
    severity: Optional[str] = None,
    limit: int = 50,
) -> List[AlertRecord]:
    """List unresolved alerts (not in 'resolved' state)."""
    query = db.query(AlertRecord).filter(AlertRecord.state != "resolved")
    if severity:
        query = query.filter(AlertRecord.severity == severity)
    return query.order_by(AlertRecord.fired_at.desc()).limit(limit).all()


def count_alerts_by_state(db: Session) -> Dict[str, int]:
    """Count alerts grouped by state."""
    counts = {}
    for state in VALID_STATES:
        counts[state] = (
            db.query(AlertRecord)
            .filter(AlertRecord.state == state)
            .count()
        )
    return counts
